### ISSUE TITLE
event model datefields

### ISSUE THREAD

**Issue by wmles** [valuehack/scholariumat#78]
Dass die Veranstaltungen i.A. ein unterschiedliches Start- und Enddatum haben können (sodass das Enddatum ignoriert wird wenn leer) ist noch nicht implementiert, oder? Dann mache ich das mal...

**Comment by MerlinB** [comment]
OOh, Interesse an der Seite :D Events haben schon ein optionales Enddatum, das angezeigt wird. Hat aber bisher keine weitere Funktionalität.

**Comment by wmles** [comment]
alles klar - dann ist ja noch einfacher, dann muss man das nur nutzen für das „intensive Orientierungscoaching”.
[ist das Absicht, dass die Veranstaltungen so komisch datumsignorant geordnet sind?]

**Comment by MerlinB** [comment]
Im Template steht: 
```
{{ object.date }}
{% if object.end_date %}
 -
  {{ object.end_date }}
{% endif %}
```
Was ist das Problem damit?

Wo siehst du die falsche Sortierung? In events.views ist der Event ListView in `get_queryset` nach `datum `sortiert und der ListView der Aufzeichnungen nach `-datum`.
